name: 'Setup Python Environment with Data Downloads'
description: 'Install dependencies and pre-download NLTK and defeatbeta-api data to prevent firewall blocks'

runs:
  using: "composite"
  steps:
    - name: Cache NLTK data
      uses: actions/cache@v3
      with:
        path: ~/nltk_data
        key: ${{ runner.os }}-nltk-data-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-nltk-data-
    
    - name: Download NLTK data
      shell: bash
      run: |
        python -c "import nltk; nltk.download('punkt', quiet=True); nltk.download('stopwords', quiet=True); nltk.download('wordnet', quiet=True); nltk.download('averaged_perceptron_tagger', quiet=True)"
    
    - name: Pre-download defeatbeta-api data
      shell: bash
      run: |
        python -c "import sys; sys.path.insert(0, 'src'); from defeatbeta_api.data.ticker import Ticker; print('defeatbeta-api data downloaded successfully')" || echo "defeatbeta-api data download skipped or failed (may not be critical)"
