name: Bug Report
description: バグレポートを作成
title: "[Bug]: "
labels: ["bug"]
assignees: ["copilot"]
body:
  - type: markdown
    attributes:
      value: |
        バグレポートをご提出いただきありがとうございます。

        💡 **GitHub Copilotを使用する場合**: Issueのコメント欄で
        `@copilot` とメンションすることで、GitHub Copilotに
        質問や分析を依頼できます。Copilotに修正とPull Request作成まで
        依頼することも可能です。
  - type: dropdown
    id: base-branch
    attributes:
      label: ベースブランチ
      description: Pull Requestのベースとなるブランチを選択してください。通常は「main」を選択します。
      options:
        - main
        - copilot/split-main-py-file
        - freature/analyze-brand
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 何が起きましたか？
      description: バグの内容を詳しく教えてください。
      placeholder: バグの詳細をここに記載してください。
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: どのような動作を期待していましたか？
      placeholder: 期待される動作をここに記載してください。
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: バグを再現するための手順を教えてください。
      placeholder: |
        1. '...' に移動
        2. '...' をクリック
        3. '...' まで下にスクロール
        4. エラーを確認
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 関連ログ
      description: 関連するログやエラーメッセージがあれば貼り付けてください。
      render: shell
    validations:
      required: false
  - type: textarea
    id: copilot-request
    attributes:
      label: GitHub Copilotへの質問（任意）
      description: GitHub Copilotに分析や質問をしたい場合は、以下のようにメンションしてください。
      placeholder: "@copilot この問題を修正し、Pull Requestを作成してください"
      value: "@copilot この問題を修正し、Pull Requestを作成してください"
    validations:
      required: false
